name: pluv
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  logger: ^2.3.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.4
  image_cropper: ^6.0.0
  google_fonts: ^6.2.0
  extended_image: ^8.1.1 #외부 이미지 표현
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  flutter_switch: ^0.3.2
  lottie: ^2.6.0

  # firebase
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.7.6
  firebase_auth: ^4.19.6
  firebase_messaging: ^14.9.3
  cloud_functions: ^4.7.5
  firebase_analytics: ^10.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icon/
    - assets/images/myicon/
    - assets/lottie/


  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900

